/* automatically generated by rust-bindgen 0.69.5 */

extern "C" {
    pub fn add_numbers(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_device_count() -> ::std::os::raw::c_int;
}
